sudo: false
os:
  - linux
language: cpp
compiler:
  - gcc
notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

script:
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake .
  - cmake --build .
