sudo: false

os:
  - linux

language: cpp
compiler: gcc

notifications:
  email: false

matrix:
  include:
    - os: linux
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - g++-7
        env:
          - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-get update -qq

#install:
#  - sudo apt-get install -qq g++-6
#  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script:
  - ./travis.sh
  - ./runall.sh
