sudo: false
os:
  - linux
language: cpp
compiler:
  - gcc
notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

script:
  - ./travis.sh
